const adventurerGear = [
  { item: "Backpack", price: 50, weight: 2, quantity: 1 },
  { item: "Bedroll", price: 25, weight: 4, quantity: 1 },
  { item: "Canteen", price: 5, weight: 1, quantity: 1 },
  { item: "Flashlight", price: 20, weight: 1, quantity: 1 },
  { item: "Flint and Steel", price: 3, weight: 1, quantity: 1 },
  { item: "Handcuffs", price: 15, weight: 2, quantity: 1 },
  { item: "Lantern", price: 25, weight: 2, quantity: 1 },
  { item: "Lockpicks", price: 200, weight: 1, quantity: 1 },
  { item: "Rope", price: 10, weight: 15, quantity: 1 },
  { item: "Shovel", price: 5, weight: 5, quantity: 1 },
  { item: "Torch", price: 5, weight: 2, quantity: 1 },
  { item: "Tool Kit", price: 200, weight: 10, quantity: 1 },
  { item: "Quiver", price: 25, weight: 2, quantity: 1 },
];

const meleeWeapons = [
  {
    item: "Dagger",
    range: "melee",
    damage: "Str+d4",
    weight: 1,
    price: 25,
    twoHanded: false,
  },
  {
    item: "Sword",
    range: "melee",
    damage: "Str+6",
    weight: 3,
    price: 200,
    notes: "parry +1",
    twoHanded: false,
  },
  {
    item: "Battle Axe",
    range: "melee",
    damage: "Str+8",
    weight: 4,
    price: 300,
    twoHanded: false,
  },
  {
    item: "Small shield",
    weight: 5,
    price: 25,
    notes: "+1 parry",
    twoHanded: false,
  },
  {
    item: "Medium shield",
    weight: 10,
    price: 50,
    notes: "+1 parry, +2 *armour",
    twoHanded: false,
  },
];

const armourStock = [
  {
    item: "Leather",
    armour: 1,
    covers: "torso, arms, legs",
    weight: 15,
    price: 50,
    notes: "medieval",
  },
  {
    item: "Chain Hauberk",
    armour: 2,
    covers: "torso, arms, legs",
    weight: 25,
    price: 300,
    notes: "medieval",
  },
  {
    item: "Steel Helmet",
    armour: 3,
    covers: "head",
    weight: 8,
    price: 75,
    notes: "50% vs head, medieval",
  },
  {
    item: "Kevlar Vest",
    armour: 2,
    covers: "torso",
    weight: 8,
    price: 250,
    notes: "modern, 4 armour vs bullets",
  },
  {
    item: "Battle Suit",
    armour: 6,
    covers: "head, torso, arms, legs",
    weight: 20,
    price: "Mil",
    notes: "near future",
  },
  {
    item: "Powered Armour",
    armour: 10,
    covers: "head, torso, arms, legs",
    weight: 0,
    price: "Mil",
    notes: "future",
  },
];

const rangedWeapons = [
  {
    item: "Revolver",
    range: "12/24/48",
    damage: "2d6+1",
    rof: 1,
    shots: 6,
    weight: 4,
    price: 200,
    ap: 1,
    notes: "none",
    twoHanded: false,
  },
  {
    item: "Handgun",
    range: "12/24/48",
    damage: "2d6",
    ap: 1,
    rof: 1,
    shots: 17,
    weight: 3,
    price: 200,
    notes: "semi-auto",
    twoHanded: false,
  },
  {
    item: "Shotgun (pump)",
    range: "12/24/48",
    damage: "1-3d6",
    ap: 0,
    rof: 1,
    shots: 6,
    price: 150,
    weight: 8,
    notes: "2 hands",
    twoHanded: true,
  },
  {
    item: "Rifle",
    range: "24/48/96",
    damage: "2d8",
    ap: 2,
    rof: 1,
    shots: 5,
    weight: 10,
    price: 300,
    notes: "2 hands",
    twoHanded: true,
  },
];

export { adventurerGear, meleeWeapons, armourStock, rangedWeapons };
