const adventurerGear = [
  { item: "Backpack", price: 50, weight: 2, quantity: 1 },
  { item: "Bedroll", price: 25, weight: 4, quantity: 1 },
  { item: "Canteen", price: 5, weight: 1, quantity: 1 },
  { item: "Flashlight", price: 20, weight: 1, quantity: 1 },
  { item: "Flint and Steel", price: 3, weight: 1, quantity: 1 },
  { item: "Handcuffs", price: 15, weight: 2, quantity: 1 },
  { item: "Lantern", price: 25, weight: 2, quantity: 1 },
  { item: "Lockpicks", price: 200, weight: 1, quantity: 1 },
  { item: "Rope", price: 10, weight: 15, quantity: 1 },
  { item: "Shovel", price: 5, weight: 5, quantity: 1 },
  { item: "Torch", price: 5, weight: 2, quantity: 1 },
  { item: "Tool Kit", price: 200, weight: 10, quantity: 1 },
  { item: "Quiver", price: 25, weight: 2, quantity: 1 },
];

const meleeWeapons = [
  {
    item: "Dagger",
    range: "melee",
    damage: "Str+d4",
    weight: 1,
    price: 25,
    twoHanded: false,
  },
  {
    item: "Sword",
    range: "melee",
    damage: "Str+6",
    weight: 3,
    price: 200,
    notes: "parry +1",
    twoHanded: false,
  },
  {
    item: "Battle Axe",
    range: "melee",
    damage: "Str+8",
    weight: 4,
    price: 300,
    twoHanded: false,
  },
  {
    item: "Small shield",
    weight: 5,
    price: 25,
    notes: "+1 parry",
    twoHanded: false,
  },
  {
    item: "Medium shield",
    weight: 10,
    price: 50,
    notes: "+1 parry, +2 *armour",
    twoHanded: false,
  },
];

const armourStock = [
  {
    item: "Leather",
    armour: 1,
    covers: "torso, arms, legs",
    weight: 15,
    price: 50,
    notes: "medieval",
  },
  {
    item: "Chain Hauberk",
    armour: 2,
    covers: "torso, arms, legs",
    weight: 25,
    price: 300,
    notes: "medieval",
  },
  {
    item: "Steel Helmet",
    armour: 3,
    covers: "head",
    weight: 8,
    price: 75,
    notes: "50% vs head, medieval",
  },
  {
    item: "Battle Suit",
    armour: 6,
    covers: "head, torso, arms, legs",
    weight: 20,
    price: "Mil",
    notes: "near future",
  },
  {
    item: "Powered Armour",
    armour: 10,
    covers: "head, torso, arms, legs",
    weight: 0,
    price: "Mil",
    notes: "future",
  },
];

const rangedWeapons = [
  {
    item: "Revolver",
    range: "12/24/48",
    damage: "2d6+1",
    rof: 1,
    shots: 6,
    weight: 4,
    price: 200,
    ap: 1,
    notes: "none",
    twoHanded: false,
  },
  {
    item: "Handgun",
    range: "12/24/48",
    damage: "2d6",
    ap: 1,
    rof: 1,
    shots: 17,
    weight: 3,
    price: 200,
    notes: "semi-auto",
    twoHanded: false,
  },
  {
    item: "Shotgun (pump)",
    range: "12/24/48",
    damage: "1-3d6",
    ap: 0,
    rof: 1,
    shots: 6,
    price: 150,
    weight: 8,
    notes: "2 hands",
    twoHanded: true,
  },
  {
    item: "Rifle",
    range: "24/48/96",
    damage: "2d8",
    ap: 2,
    rof: 1,
    shots: 5,
    weight: 10,
    price: 300,
    notes: "2 hands",
    twoHanded: true,
  },
];

const skillList = {
  boating: { name: "Boating", attribute: "Agility", score: 4 },
  climbing: { name: "Climbing", attribute: "Strength", score: 4 },
  driving: { name: "Driving", attribute: "Agility", score: 4 },
  fighting: { name: "Fighting", attribute: "Agility", score: 4 },
  gambling: { name: "Gambling", attribute: "Smarts", score: 4 },
  healing: { name: "Healing", attribute: "Smarts", score: 4 },
  intimidation: { name: "Intimidation", attribute: "Spirit", score: 4 },
  investigation: { name: "Investigation", attribute: "Smarts", score: 4 },
  knowledge: { name: "Knowledge", attribute: "Smarts", score: 4 },
  lockpicking: { name: "Lockpicking", attribute: "Agility", score: 4 },
  notice: { name: "Notice", attribute: "Smarts", score: 4 },
  persuasion: { name: "Persuasion", attribute: "Spirit", score: 4 },
  piloting: { name: "Piloting", attribute: "Agility", score: 4 },
  repair: { name: "Repair", attribute: "Smarts", score: 4 },
  riding: { name: "Riding", attribute: "Agility", score: 4 },
  shooting: { name: "Shooting", attribute: "Agility", score: 4 },
  stealth: { name: "Stealth", attribute: "Agility", score: 4 },
  streetwise: { name: "Streetwise", attribute: "Smarts", score: 4 },
  survival: { name: "Survival", attribute: "Smarts", score: 4 },
  swimming: { name: "Swimming", attribute: "Agility", score: 4 },
  taunt: { name: "Taunt", attribute: "Smarts", score: 4 },
  throwing: { name: "Throwing", attribute: "Agility", score: 4 },
  tracking: { name: "Tracking", attribute: "Smarts", score: 4 },
};

export { adventurerGear, meleeWeapons, armourStock, rangedWeapons, skillList };
